

const paragraph = [
    "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair. We had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.",

    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. The road to success is never easy; it is filled with challenges, failures, and setbacks. However, those who persevere, learn from their mistakes, and adapt to change always find a way forward. Every great achievement begins with a single step, and consistency is what turns those steps into a journey of success. Believe in yourself, trust the process, and never stop improving.",

    "Hinduism is one of the oldest and most diverse religions in the world, deeply rooted in spirituality, philosophy, and tradition. Unlike many religions with a single founder or central doctrine, Hinduism is a way of life that embraces multiple paths to self-realization and enlightenment. The sacred texts, including the Vedas, Upanishads, Bhagavad Gita, and Ramayana, provide guidance on dharma (duty), karma (action and its consequences), and moksha (liberation from the cycle of birth and rebirth). Hinduism teaches that the ultimate reality, Brahman, is present in all living beings, emphasizing the interconnectedness of life. Through practices such as yoga, meditation, and devotion to deities like Vishnu, Shiva, and Devi, followers seek inner peace and spiritual growth. The festival celebrations, rituals, and traditions reflect a deep reverence for nature, harmony, and cosmic balance. At its core, Hinduism encourages self-inquiry, compassion, and the pursuit of truth, allowing individuals to choose their own spiritual journey toward enlightenment.",

    "Space exploration has always been a testament to human curiosity and ambition. From the first moon landing to the recent Mars rover missions, scientists and astronauts continue to push the boundaries of what is possible. With advancements in technology, space agencies like NASA, SpaceX, and ISRO are developing plans for deep-space travel, lunar bases, and even human settlements on Mars. The idea of interplanetary colonization is no longer science fiction but a real possibility for the future. However, space exploration also brings challenges, including the need for sustainable resources, protection against cosmic radiation, and ethical considerations regarding extraterrestrial environments. As we venture further into the cosmos, our responsibility is to explore wisely, ensuring that space remains a frontier of discovery and innovation.",

    "The world of literature is a vast and diverse landscape, filled with stories, ideas, and emotions that transcend time and place. From the epic poems of Homer to the modern novels of Toni Morrison, literature has the power to transport us to different worlds, challenge our perspectives, and inspire our imaginations. Through the written word, authors explore the complexities of human experience, from love and loss to joy and sorrow. Literature also serves as a mirror to society, reflecting its values, beliefs, and struggles. By reading widely and critically, we can gain insight into the human condition, cultivate empathy and understanding, and appreciate the beauty of language. Whether we are drawn to classic works of fiction, contemporary poetry, or genre-bending narratives, literature offers a window into the richness and diversity of the human spirit.",

    "The world of art is a vibrant and dynamic realm, where creativity, imagination, and expression converge to create beauty, meaning, and emotion. From the ancient cave paintings of Lascaux to the contemporary installations of Yayoi Kusama, art has the power to inspire, provoke, and transform. Artists use a variety of mediums, techniques, and styles to convey their ideas and visions, from painting and sculpture to photography and performance. Through their work, artists explore themes such as identity, memory, nature, and society, inviting viewers to engage with the world in new and unexpected ways. Art also plays a vital role in cultural expression, social commentary, and political activism, challenging norms and sparking dialogue. By experiencing art in its many forms, we can connect with our shared humanity, celebrate diversity, and appreciate the power of creativity to shape our world.",

    "The world of music is a universal language that transcends boundaries of culture, geography, and time. From the ancient rhythms of tribal drumming to the modern beats of electronic dance music, music has the power to evoke emotions, tell stories, and bring people together. Musicians use a wide range of instruments, genres, and styles to create melodies, harmonies, and rhythms that resonate with listeners around the globe. Whether we are listening to a symphony by Beethoven, a jazz improvisation by Miles Davis, or a pop song by Beyoncé, music has the ability to move us, inspire us, and connect us to something greater than ourselves. Through music, we can express our deepest feelings, share our experiences, and celebrate the diversity of human creativity. As we explore the world of music, we discover new sounds, new voices, and new perspectives that enrich our lives and expand our horizons.",

    "The world of science is a fascinating and ever-changing domain, where curiosity, observation, and experimentation drive discovery and innovation. From the laws of physics to the structure of DNA, scientists explore the natural world to uncover its mysteries and unlock its secrets. Through research, analysis, and collaboration, scientists develop theories, conduct experiments, and test hypotheses to expand our understanding of the universe. Science also plays a crucial role in addressing global challenges, such as climate change, pandemics, and biodiversity loss, by providing evidence-based solutions and informing public policy. By engaging with scientific ideas and principles, we can appreciate the wonders of the cosmos, the complexity of life, and the power of human ingenuity. Whether we are studying the stars, exploring the depths of the ocean, or developing new technologies, science offers a window into the beauty and complexity of the natural world.",

    "Mental health is just as important as physical health, yet it is often overlooked. In a world that constantly demands productivity and success, people tend to ignore the signs of stress, anxiety, and emotional exhaustion. Prioritizing mental well-being means taking the time to rest, reflect, and seek help when needed. Engaging in activities that bring joy, maintaining strong relationships, and practicing mindfulness can significantly improve one's state of mind. A healthy mind leads to a more balanced life, where challenges become easier to navigate. It is crucial to break the stigma surrounding mental health and encourage open conversations, ensuring that everyone receives the support they need to thrive.",

    "Personal growth is a continuous journey, not a destination. Every challenge faced, every lesson learned, and every failure overcome contributes to shaping a stronger, wiser individual. Growth comes from stepping outside one's comfort zone, embracing new experiences, and pushing beyond self-imposed limits. It requires patience, persistence, and a mindset that welcomes change. The path of self-improvement is not always easy, but the rewards are immense. Developing good habits, learning new skills, and fostering a positive attitude lead to greater confidence and success. Those who commit to personal growth understand that the best investment one can make is in oneself.",
    
    "Nature is a masterpiece of beauty and complexity, a perfect balance of life and harmony. From the towering mountains that touch the sky to the deepest oceans that hide countless mysteries, every aspect of nature is a marvel. The gentle rustling of leaves, the rhythmic waves of the sea, and the soothing chirps of birds remind us of the serenity that the natural world offers. However, human activity has disrupted this balance, causing environmental damage that threatens the very foundation of life. It is our responsibility to protect and preserve nature, not only for ourselves but for future generations. By appreciating and respecting the environment, we ensure that its wonders remain untouched for years to come.",

    "Discipline is the foundation of success, the bridge between goals and accomplishments. It is the ability to stay committed to a task even when motivation fades. Those who master discipline understand that success is not achieved overnight but through consistent effort and perseverance. Whether in academics, sports, or personal growth, discipline enables individuals to stay focused and resilient in the face of challenges. It teaches patience, responsibility, and the value of hard work. While talent and intelligence may open doors, it is discipline that ensures sustained success. In a world full of distractions, those who cultivate discipline stand out as leaders and achievers.",

    "The vastness of the universe is beyond human comprehension. Billions of galaxies, each containing millions of stars, stretch across the cosmic landscape, forming a spectacle of celestial beauty. Scientists have long sought to uncover the mysteries of space, from black holes that devour light to exoplanets that may harbor life. The dream of interstellar travel, once confined to science fiction, is slowly becoming a reality with advancements in space technology. As humanity ventures beyond Earth, we must consider the ethical and scientific implications of colonizing other planets. The universe holds endless possibilities, and with each discovery, we take one step closer to understanding our place among the stars.",

    "Deep in the heart of the forest, a small cabin stood untouched by time. Its wooden walls whispered stories of the past, and the flickering candlelight inside painted shadows that danced with the wind. The old man who lived there had spent decades in solitude, accompanied only by the chirping of birds and the rustling of leaves. One evening, a traveler knocked on his door, seeking shelter from the storm. As they sat by the fire, the man shared tales of forgotten legends, of hidden treasures buried beneath the roots of ancient trees, and of a world beyond the wilderness where dreams took flight.",

    "Space exploration has always been a testament to human curiosity and ambition. From the first moon landing to the recent Mars rover missions, scientists and astronauts continue to push the boundaries of what is possible. With advancements in technology, space agencies like NASA, SpaceX, and ISRO are developing plans for deep-space travel, lunar bases, and even human settlements on Mars. The idea of interplanetary colonization is no longer science fiction but a real possibility for the future. However, space exploration also brings challenges, including the need for sustainable resources, protection against cosmic radiation, and ethical considerations regarding extraterrestrial environments. As we venture further into the cosmos, our responsibility is to explore wisely, ensuring that space remains a frontier of discovery and innovation.",

    "Hinduism, often called Sanatana Dharma, is a spiritual tradition that intertwines philosophy, devotion, and ethics. It expounds the cosmic cycle of existence, where life, death, and rebirth are governed by the immutable law of karma. The concept of maya, or illusion, veils the true nature of reality, leading souls to perceive separateness from the divine. Advaita Vedanta proclaims the oneness of the individual soul and the ultimate reality, while other schools emphasize devotion and surrender to a higher power. The pursuit of truth can take many forms—through wisdom, selfless action, or meditative discipline—all leading toward liberation and transcendence."
];


